### PR TITLE
Add rmw_publisher_count_non_local_matched_subscriptions

### PR DESCRIPTION
**Pull request by jfinken**
Add this method but set an error message and return `RMW_RET_UNSUPPORTED`

### CODE REVIEW

**Review by mauropasse — APPROVED** [review]

**Review by alsora — APPROVED** [review]

**Comment by jfinken** [comment]
Regarding the build failures.  Perhaps this cannot be built with Github CI?  [All Github CI jobs were removed in Sept. 2022](https://github.com/ros2/rmw_cyclonedds/commit/cc0510b9003f2184146c0a094545451ce14ec72f#diff-3e5db3edbb6f0b886dd8743b4e7cdb8525ababffa00397e1a52fdbd675ee2bd8), _after_ the tagged 1.3.3 humble branch we have here.

**Comment by alsora** [comment]
@jfinken feel free to ignore those CI checks.
They are not "ours" and are building the repo using vanilla ROS dependencies. Our branches only work with our specific versions of the depedndencies

**Comment by jfinken** [comment]
> @jfinken feel free to ignore those CI checks. They are not "ours" and are building the repo using vanilla ROS dependencies. Our branches only work with our specific versions of the depedndencies

Ok sounds good, thanks @alsora.  Merging.

**Comment by mauropasse** [comment]
We might want to open this PR to `rmw_cyclonedds` once the eProsima PRs go in https://github.com/ros2/rclcpp/pull/2338

**Pull request merged**
